---
- name: Get join-token for worker nodes
  set_fact:
    join_token_worker: "{{ hostvars[groups['swarm_manager'][0]].result.swarm_facts.JoinTokens.Worker }}"

- name: Add nodes
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_host }}"
    join_token: "{{ join_token_worker }}"
    remote_addrs: "{{ groups['swarm_manager'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"
