---
- name: Install necessary packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
      - net-tools
      - python3-pip

- name: ensure required pip-packages are installed
  pip:
    name: 
      - docker
      - PyYAML
      - docker-compose