---
- name: Check docker is exist in current host
  command: which docker
  check_mode: false
  changed_when: false
  failed_when: false
  register: docker_installed

- name: debug docker check exist
  when: not docker_installed.rc != 0 and docker_installed.rc != 127
  debug:
    msg: docker is existed

- name: install docker
  when: docker_installed.rc != 0 and docker_installed.rc != 127
  block:
    - name: is docker exist
      when: vars.mode == "debug"
      debug:
        msg: docker is not exist will install

    - name: Add Docker s GPG key for ubuntu from official site
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker
    
    - name: Verify gpg key with the fingerprint
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

    - name: Configure Docker for ubuntu stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags:
        - docker

- name: Check docker compose exist
  command: which docker-compose
  check_mode: false
  changed_when: false
  failed_when: false
  register: docker_compose_installed

- name: install docker-compose
  when: docker_compose_installed.rc != 0 and docker_compose_installed.rc != 127
  get_url:
    url : "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'